"use client";

import { useMemo, useState } from "react";
import { useIFProgress } from "@/lib/if-progress";
import { CASE_RESULTS, R_AND_D_HISTORY, money } from "./FinancialStatementCase";
import StatementInvestigationShell, {
  DefinitionStrip,
  StatementChoice,
  StatementFeedback,
  StatementMetric,
  StatementPanel,
  type StatementInvestigationStep,
  type StatementSceneProps,
} from "./StatementInvestigationShell";

const SLUG = "if-4-5-repair-the-investor-view";
const STEPS: readonly StatementInvestigationStep[] = [
  { label: "Set the reporting date", title: "Do not apply an old repair to a current statement blindly", guide: "The source's lease adjustment solved an off-balance-sheet problem. Current Topic 842 and IFRS 16 statements generally start with a recognized right-of-use asset and lease liability.", instruction: "Compare the source-era and current starting points.", next: "Price the promise" },
  { label: "Price the promise", title: "Turn contractual lease payments into present value", guide: "The source's economic logic remains useful: a fixed lease commitment behaves like a financing claim. Present value measures the commitment today.", instruction: "Run the twelve-payment present-value scan.", next: "Build the research asset" },
  { label: "Build the research asset", title: "Replace one expense with an explicit analyst model", guide: "The R&D recast requires an assumed useful life, historical expenses, an unamortized asset, and current amortization. None of those assumptions should be hidden.", instruction: "Construct the five-year research asset.", next: "Interpret the repair" },
  { label: "Interpret the repair", title: "Higher adjusted profit does not guarantee a higher return", guide: "Capitalizing R&D can raise adjusted operating income and invested capital at the same time. Return on capital depends on both effects.", instruction: "Resolve the framework and return checks, then save the memo.", next: "Open Lesson 4.6" },
];

export default function AnalystAdjustmentsJourney() {
  return <StatementInvestigationShell lessonSlug={SLUG} ariaLabel="Analyst adjustments investigation" steps={STEPS} renderStep={(step, onComplete) => step === 0 ? <ReportingDate onComplete={onComplete} /> : step === 1 ? <LeasePresentValue onComplete={onComplete} /> : step === 2 ? <ResearchAsset onComplete={onComplete} /> : <AdjustmentInterpretation onComplete={onComplete} />} nextLesson={{ href: "/lessons/if-4-6-trace-cash-to-the-investor", label: "Continue to the cash-flow scanner" }} />;
}

function ReportingDate({ onComplete }: StatementSceneProps) {
  const [selected, setSelected] = useState(""); const correct = selected === "inspect";
  return <div><div className="grid gap-4 lg:grid-cols-2"><StatementPanel><div className="ops-caption text-[12px] text-accent-amber">Source-era problem</div><div className="mt-1 text-lg font-semibold text-white">Operating lease commitments were often off balance sheet</div><p className="ops-body mt-3 text-[15px] text-slate-300">The analyst discounted footnote commitments, added lease debt and a leased asset, and restated operating income.</p></StatementPanel><StatementPanel><div className="ops-caption text-[12px] text-accent-cyan">Current reported starting point</div><div className="mt-1 text-lg font-semibold text-white">Cedar Works already reports both sides</div><div className="mt-4 grid grid-cols-2 gap-3"><StatementMetric label="Right-of-use asset" value="$30m" tone="cyan" /><StatementMetric label="Lease liabilities" value="$30m" tone="amber" /></div></StatementPanel></div><div className="mt-5 rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="ops-caption text-[12px] text-slate-500">Current-standard reconciliation</div><p className="mt-2 text-sm leading-6 text-slate-300"><span className="font-semibold text-white">US GAAP Topic 842:</span> generally recognizes operating and finance lease assets and liabilities, while subsequent expense presentation differs by lease type. <span className="font-semibold text-white">IFRS 16:</span> generally uses one lessee model for nearly all leases, subject to exemptions.</p></div><p className="ops-body-strong mt-6 text-lg text-white">What should the analyst do first?</p><div className="mt-4 space-y-3"><StatementChoice onClick={() => setSelected("double")} disabled={Boolean(selected)} incorrect={selected === "double"}>Add the $30m lease liability again because the source says leases are debt.</StatementChoice><StatementChoice onClick={() => setSelected("inspect")} disabled={Boolean(selected)} correct={selected === "inspect"}>Inspect what the current statement already recognizes, then adjust only for a defined analytical purpose without double counting.</StatementChoice></div>{selected && <><StatementFeedback correct={correct}>{correct ? "Date, framework, and existing recognition determine the starting point. The source's economic idea survives; the mechanical starting point changed." : "Adding a liability already reported would double count the claim."}</StatementFeedback><button type="button" onClick={onComplete} className="mt-4 rounded-full border border-accent-green/40 bg-accent-green/10 px-5 py-2 text-sm font-semibold text-accent-green">Lock the reporting date</button></>}</div>;
}

function LeasePresentValue({ onComplete }: StatementSceneProps) {
  const [calculated, setCalculated] = useState(false);
  return <div><DefinitionStrip term="present value of lease commitments">The value today of fixed future lease payments discounted at a rate reflecting the financing claim and timing.</DefinitionStrip><StatementPanel className="mt-5"><div className="grid gap-3 sm:grid-cols-3"><StatementMetric label="Annual payment" value="$1.0m" /><StatementMetric label="End-of-year payments" value="12" /><StatementMetric label="Discount rate" value="4.0%" tone="amber" /></div><div className="mt-5 rounded-xl border border-white/10 bg-white/[0.03] p-4 text-center"><div className="ops-caption text-[12px] text-slate-500">Ordinary-annuity present value</div><div className="mt-2 break-words text-lg font-semibold tabular-nums text-white">$1m × [1 − (1.04)<sup>−12</sup>] ÷ 0.04</div></div></StatementPanel><button type="button" onClick={() => setCalculated(true)} className="mt-4 rounded-full border border-accent-amber/40 bg-accent-amber/10 px-5 py-2 text-sm font-semibold text-accent-amber">Discount all 12 payments</button>{calculated && <><div className="mt-4 grid gap-3 sm:grid-cols-2"><StatementMetric label="Present value" value="$9.385m" detail="Assumes end-of-year payments and the stated 4% rate" tone="green" /><StatementMetric label="Analytical meaning" value="Financing claim" detail="Payment timing, options, variable rent, and contract details can change measurement" tone="cyan" /></div><StatementFeedback correct>The calculation verifies the source method. It is not permission to add $9.385m to a statement that already recognizes the same obligation.</StatementFeedback><button type="button" onClick={onComplete} className="mt-4 rounded-full border border-accent-green/40 bg-accent-green/10 px-5 py-2 text-sm font-semibold text-accent-green">Save the lease calculation</button></>}</div>;
}

function ResearchAsset({ onComplete }: StatementSceneProps) {
  const [built, setBuilt] = useState(false);
  const researchAsset = useMemo(() => R_AND_D_HISTORY.reduce((sum, row) => sum + row.expense * row.unamortized, 0), []);
  return <div><div className="grid gap-4 lg:grid-cols-2"><StatementPanel><div className="ops-caption text-[12px] text-accent-cyan">Reported accounting</div><p className="ops-body mt-2 text-[15px] text-slate-300"><span className="font-semibold text-white">US GAAP:</span> internally incurred R&D is generally expensed, with specific exceptions. <span className="font-semibold text-white">IAS 38:</span> research is expensed; qualifying development is capitalized after recognition criteria are met.</p></StatementPanel><StatementPanel><div className="ops-caption text-[12px] text-accent-amber">Damodaran analyst recast</div><p className="ops-body mt-2 text-[15px] text-slate-300">Choose an economic life, collect historical R&D, construct the unamortized research asset, and replace current expense with model amortization.</p></StatementPanel></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[minmax(0,1fr)_72px_88px_78px] gap-2 border-b border-white/10 bg-white/[0.03] px-3 py-3 text-[12px] text-slate-500 sm:px-4"><span>Expense year</span><span className="text-right">R&D</span><span className="text-right">Unamortized</span><span className="text-right">Asset</span></div>{R_AND_D_HISTORY.map((row) => <div key={row.age} className="grid grid-cols-[minmax(0,1fr)_72px_88px_78px] gap-2 border-b border-white/10 px-3 py-3 text-sm last:border-b-0 sm:px-4"><span className="text-slate-300">{row.label}</span><span className="text-right tabular-nums text-white">{money(row.expense)}</span><span className="text-right tabular-nums text-slate-300">{Math.round(row.unamortized * 100)}%</span><span className="text-right tabular-nums text-accent-cyan">{built ? money(row.expense * row.unamortized) : "—"}</span></div>)}</div><button type="button" onClick={() => setBuilt(true)} className="mt-4 rounded-full border border-accent-amber/40 bg-accent-amber/10 px-5 py-2 text-sm font-semibold text-accent-amber">Build the research asset</button>{built && <><div className="mt-4 grid gap-3 sm:grid-cols-3"><StatementMetric label="Research asset" value={money(researchAsset)} tone="cyan" /><StatementMetric label="Current amortization" value="$11.0m" detail="20% of the four prior-year expenses" tone="amber" /><StatementMetric label="Adjusted operating income" value="$69.0m" detail="$60m + $20m − $11m" tone="green" /></div><button type="button" onClick={onComplete} className="mt-4 rounded-full border border-accent-green/40 bg-accent-green/10 px-5 py-2 text-sm font-semibold text-accent-green">Verify the R&D model</button></>}</div>;
}

function AdjustmentInterpretation({ onComplete }: StatementSceneProps) {
  const { statementBrief, saveStatementBrief } = useIFProgress(); const [framework, setFramework] = useState(""); const [returnAnswer, setReturnAnswer] = useState("");
  const finish = () => { saveStatementBrief({ ...statementBrief, adjustmentFinding: "Cedar Works already reports a $30m right-of-use asset and $30m lease liability, so the source-era lease adjustment must not be added twice. The OPS five-year R&D recast creates a $50.2m research asset, raises adjusted operating income to $69m, and lowers adjusted return on capital from 25.7% to 23.0%." }); onComplete(); };
  return <div className="space-y-5"><StatementPanel><div className="ops-caption text-[12px] text-accent-amber">Framework check</div><p className="ops-body-strong mt-2 text-lg text-white">Which statement is accurate?</p><div className="mt-4 space-y-3"><StatementChoice onClick={() => setFramework("same")} disabled={Boolean(framework)} incorrect={framework === "same"}>US GAAP, IFRS, and the analyst R&D recast all require the same capitalization.</StatementChoice><StatementChoice onClick={() => setFramework("different")} disabled={Boolean(framework)} correct={framework === "different"}>Reported treatment depends on the framework; the Damodaran recast is a separate analyst model with explicit assumptions.</StatementChoice></div>{framework && <StatementFeedback correct={framework === "different"}>Separate the reporting rule from the investor&apos;s analytical adjustment.</StatementFeedback>}</StatementPanel>{framework && <StatementPanel><div className="ops-caption text-[12px] text-accent-amber">Return check</div><p className="ops-body-strong mt-2 text-lg text-white">Adjusted operating income rises from $60m to $69m. Why can return on capital fall from {CASE_RESULTS.baseReturnOnCapital}% to {CASE_RESULTS.adjustedReturnOnCapital}%?</p><div className="mt-4 space-y-3"><StatementChoice onClick={() => setReturnAnswer("capital")} disabled={Boolean(returnAnswer)} correct={returnAnswer === "capital"}>The $50.2m research asset increases invested capital by more than the after-tax profit increase improves the numerator.</StatementChoice><StatementChoice onClick={() => setReturnAnswer("impossible")} disabled={Boolean(returnAnswer)} incorrect={returnAnswer === "impossible"}>It cannot fall when operating income rises.</StatementChoice></div>{returnAnswer && <StatementFeedback correct={returnAnswer === "capital"}>A return is a ratio. Both adjusted profit and adjusted invested capital matter.</StatementFeedback>}</StatementPanel>}{framework && returnAnswer && <button type="button" onClick={finish} className="rounded-full border border-accent-green/40 bg-accent-green/10 px-5 py-2 text-sm font-semibold text-accent-green">File the analyst adjustment memo</button>}</div>;
}
