"use client";

import { useState } from "react";
import { motion, AnimatePresence, useReducedMotion } from "motion/react";
import { cn } from "@/lib/utils";
import { InteractiveFrame, TryItTag } from "./shared";

type Mode = "corporate" | "personal";

const STEPS: Record<Mode, { n: number; title: string; body: string }[]> = {
  corporate: [
    {
      n: 1,
      title: "Raise cash",
      body: "Company sells stocks or bonds to raise money.",
    },
    {
      n: 2,
      title: "Invest in real assets",
      body: "Company buys factories, equipment, technology, brand assets, or R&D.",
    },
    {
      n: 3,
      title: "Generate cash from operations",
      body: "Business activity produces revenue and cash flow.",
    },
    {
      n: 4,
      title: "Reinvest",
      body: "Company puts cash back into the business for growth.",
    },
    {
      n: 5,
      title: "Return cash to investors",
      body: "Company pays interest, repays debt, pays dividends, or buys back shares.",
    },
  ],
  personal: [
    {
      n: 1,
      title: "Raise cash",
      body: "Cash is raised from financial institutions, such as through loans or mortgages.",
    },
    {
      n: 2,
      title: "Invest in real assets",
      body: "Cash is invested in education, housing, or human capital.",
    },
    {
      n: 3,
      title: "Generate cash from labor",
      body: "Cash is generated by labor supply.",
    },
    {
      n: 4,
      title: "Consume or reinvest",
      body: "Cash is consumed or reinvested in real assets.",
    },
    {
      n: 5,
      title: "Invest in financial assets",
      body: "Cash is invested in stocks, bonds, retirement accounts, or savings vehicles.",
    },
  ],
};

const OBJECTIVE: Record<Mode, { label: string; body: string }> = {
  corporate: {
    label: "Corporate objective",
    body: "The corporate objective is to create and maximize shareholder value.",
  },
  personal: {
    label: "Personal objective",
    body: "The personal objective is to maximize lifetime happiness or expected utility.",
  },
};

export default function CorporatePersonalCashFlowToggle({
  onComplete,
}: {
  onComplete?: () => void;
}) {
  const [mode, setMode] = useState<Mode>("corporate");
  const [active, setActive] = useState<number | null>(null);
  const [visited, setVisited] = useState<Set<number>>(new Set());
  const reduce = useReducedMotion();
  const steps = STEPS[mode];

  const select = (n: number) => {
    setActive(n);
    setVisited((prev) => {
      const next = new Set(prev);
      next.add(n);
      if (next.size === 5) onComplete?.();
      return next;
    });
  };

  const switchMode = (m: Mode) => {
    setMode(m);
    setActive(null);
    setVisited(new Set());
  };

  return (
    <div className="space-y-5">
      <InteractiveFrame>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2.5">
            <TryItTag />
            <span className="ops-caption text-[11px] text-slate-400">
              Cash-flow system
            </span>
          </div>
          <div className="inline-flex rounded-full border border-white/15 bg-ink-950/60 p-1">
            <button
              type="button"
              aria-pressed={mode === "corporate"}
              onClick={() => switchMode("corporate")}
              className={cn(
                "rounded-full px-3.5 py-1.5 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-cyan/50",
                mode === "corporate"
                  ? "bg-accent-cyan/20 text-accent-cyan"
                  : "text-slate-300 hover:text-slate-100",
              )}
            >
              Corporate
            </button>
            <button
              type="button"
              aria-pressed={mode === "personal"}
              onClick={() => switchMode("personal")}
              className={cn(
                "rounded-full px-3.5 py-1.5 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-cyan/50",
                mode === "personal"
                  ? "bg-accent-cyan/20 text-accent-cyan"
                  : "text-slate-300 hover:text-slate-100",
              )}
            >
              Personal
            </button>
          </div>
        </div>

        {/* Flow map */}
        <div className="mt-5 overflow-x-auto">
          <div className="flex min-w-[640px] items-stretch gap-2">
            {steps.map((s, i) => {
              const isActive = active === s.n;
              const isVisited = visited.has(s.n);
              return (
                <div key={s.n} className="flex items-center gap-2">
                  <button
                    type="button"
                    aria-pressed={isActive}
                    onClick={() => select(s.n)}
                    className={cn(
                      "flex w-32 flex-col items-start rounded-xl border p-4 text-left transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-cyan/50",
                      isActive
                        ? "border-accent-cyan bg-accent-cyan/10"
                        : isVisited
                          ? "border-accent-cyan/40 bg-accent-cyan/5"
                          : "border-white/15 bg-white/[0.02] hover:border-white/30",
                    )}
                  >
                    <span className="ops-caption text-[10px] text-slate-500">
                      Step {s.n}
                    </span>
                    <span className="font-display mt-1.5 text-[15px] font-medium leading-snug text-slate-100">
                      {s.title}
                    </span>
                    <span
                      className={cn(
                        "ops-caption mt-2 text-[10px]",
                        isVisited ? "text-accent-green" : "text-slate-500",
                      )}
                    >
                      {isVisited ? "✓ viewed" : "tap to view"}
                    </span>
                  </button>
                  {i < steps.length - 1 && (
                    <span className="text-lg text-accent-cyan" aria-hidden>
                      →
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        <AnimatePresence mode="wait">
          {active !== null && (
            <motion.div
              key={`${mode}-${active}`}
              initial={reduce ? false : { opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="ops-definition-card mt-5 p-5"
            >
              <div className="ops-caption text-[11px] text-accent-cyan">
                Step {active}
              </div>
              <p className="ops-definition mt-2.5 text-[16px]">
                {steps.find((s) => s.n === active)?.body}
              </p>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="mt-5 rounded-xl border border-white/15 bg-ink-950/60 p-5">
          <div className="ops-caption text-[11px] text-slate-400">
            {OBJECTIVE[mode].label}
          </div>
          <p className="ops-definition mt-2 text-[16px]">
            {OBJECTIVE[mode].body}
          </p>
        </div>
      </InteractiveFrame>
    </div>
  );
}
